# This is a sample TOML file for transocks.

listen = "localhost:1081"

proxy_url = "socks5://10.20.30.40:1080"  # for SOCKS5 server
#proxy_url = "http://10.20.30.40:3128"   # for HTTP proxy server

log_level = "debug"
log_file = "/var/log/transocks.log"
